import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';

import { AppSidebar } from '@/components/layouts/app-sidebar';
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';
import TanstackProvider from '@/providers/tanstack-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <main>
                <SidebarTrigger />
                {children}
                <Toaster position="top-center" richColors />
              </main>
            </SidebarInset>
          </SidebarProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
